spring.application.name=ms-core-data
server.port=8081
spring.docker.compose.enabled=false
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/RIntellix}
spring.data.mongodb.database=RIntellix
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.es.NTTEnterprise.RIntellix.ms_core_data=DEBUG
logging.level.org.springframework.kafka=DEBUG
# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=1
spring.kafka.producer.retries=3
spring.kafka.producer.properties.linger.ms=10
spring.kafka.producer.properties.client.dns.lookup=use_all_dns_ips
spring.kafka.properties.api.version.request.timeout.ms=10000

# Kafka Topics
scoring.kafka.topic.generation=GenerateScoring
scoring.kafka.topic.save=SaveScoring
scoring.kafka.topic.persist=PersistScoring

# Kafka Consumer Configuration for Scoring Consumer
scoring.kafka.consumer.group-id=ms-core-data-standalone
scoring.kafka.consumer.max-poll-records=100
scoring.kafka.consumer.auto-offset-reset=earliest
scoring.kafka.consumer.enable-auto-commit=false
scoring.kafka.consumer.session-timeout=30000

# Retry Configuration
scoring.kafka.consumer.retry.max-attempts=3
scoring.kafka.consumer.retry.initial-delay=100
scoring.kafka.consumer.retry.max-delay=900

# Deserialization Configuration
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=ScoringMessage:es.NTTEnterprise.RIntellix.ms_core_data.application.dtos.input.ScoringConsumerMessageDTO
spring.kafka.consumer.properties.spring.json.trusted.packages=es.NTTEnterprise.RIntellix.ms_core_data.*


