package es.NTTEnterprise.RIntellix.ms_core_data.application.dtos.input;

import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;

/**
 * Input DTO for the POST endpoint that persists an AI-generated risk report.
 * Field names follow the "reports" collection schema (snake_case) so the body
 * sent by ms-reporting maps directly. The {@code file_path} field is optional;
 * every other field is required by the schema.
 *
 * @author Lucía Fernández Mancebo
 * @date 29/03/2026
 */
public class CreateReportDTO {

    @NotBlank(message = "Party ID must be provided")
    @JsonProperty("party_id")
    private String partyId;

    @NotBlank(message = "Request ID must be provided")
    @JsonProperty("request_id")
    private String requestId;

    @NotBlank(message = "Scoring ID must be provided")
    @JsonProperty("scoring_id")
    private String scoringId;

    @NotBlank(message = "Report type must be provided")
    @JsonProperty("report_type")
    private String reportType;

    @NotBlank(message = "Title must be provided")
    @JsonProperty("title")
    private String title;

    @NotBlank(message = "AI summary must be provided")
    @JsonProperty("ai_summary")
    private String aiSummary;

    @NotBlank(message = "Risk analysis must be provided")
    @JsonProperty("risk_analysis")
    private String riskAnalysis;

    @NotEmpty(message = "Risk factors must be provided and not empty")
    @Valid
    @JsonProperty("risk_factors")
    private List<RiskFactorDTO> riskFactors;

    @NotEmpty(message = "Recommendations must be provided and not empty")
    @JsonProperty("recommendations")
    private List<String> recommendations;

    // Optional: the PDF binary storage target may not be set.
    @JsonProperty("file_path")
    private String filePath;

    @NotNull(message = "File size (bytes) must be provided")
    @JsonProperty("file_size_bytes")
    private Integer fileSizeBytes;

    @NotBlank(message = "Generated by must be provided")
    @JsonProperty("generated_by")
    private String generatedBy;

    @NotNull(message = "Generated date must be provided")
    @JsonProperty("generated_date")
    private Date generatedDate;

    @NotNull(message = "Generation time (ms) must be provided")
    @JsonProperty("generation_time_ms")
    private Integer generationTimeMs;

    @NotBlank(message = "Model version must be provided")
    @JsonProperty("model_version")
    private String modelVersion;

    @NotBlank(message = "Language must be provided")
    @JsonProperty("language")
    private String language;

    public CreateReportDTO() {
    }

    /**
     * Nested DTO for each identified risk factor.
     */
    public static class RiskFactorDTO {

        @NotBlank(message = "Risk factor name must be provided")
        @JsonProperty("factor")
        private String factor;

        @NotBlank(message = "Risk factor severity must be provided")
        @JsonProperty("severity")
        private String severity;

        @NotBlank(message = "Risk factor description must be provided")
        @JsonProperty("description")
        private String description;

        public RiskFactorDTO() {
        }

        public String getFactor() {
            return factor;
        }

        public void setFactor(String factor) {
            this.factor = factor;
        }

        public String getSeverity() {
            return severity;
        }

        public void setSeverity(String severity) {
            this.severity = severity;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }
    }

    // Getters and Setters

    public String getPartyId() {
        return partyId;
    }

    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public String getScoringId() {
        return scoringId;
    }

    public void setScoringId(String scoringId) {
        this.scoringId = scoringId;
    }

    public String getReportType() {
        return reportType;
    }

    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAiSummary() {
        return aiSummary;
    }

    public void setAiSummary(String aiSummary) {
        this.aiSummary = aiSummary;
    }

    public String getRiskAnalysis() {
        return riskAnalysis;
    }

    public void setRiskAnalysis(String riskAnalysis) {
        this.riskAnalysis = riskAnalysis;
    }

    public List<RiskFactorDTO> getRiskFactors() {
        return riskFactors;
    }

    public void setRiskFactors(List<RiskFactorDTO> riskFactors) {
        this.riskFactors = riskFactors;
    }

    public List<String> getRecommendations() {
        return recommendations;
    }

    public void setRecommendations(List<String> recommendations) {
        this.recommendations = recommendations;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Integer getFileSizeBytes() {
        return fileSizeBytes;
    }

    public void setFileSizeBytes(Integer fileSizeBytes) {
        this.fileSizeBytes = fileSizeBytes;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }

    public Date getGeneratedDate() {
        return generatedDate;
    }

    public void setGeneratedDate(Date generatedDate) {
        this.generatedDate = generatedDate;
    }

    public Integer getGenerationTimeMs() {
        return generationTimeMs;
    }

    public void setGenerationTimeMs(Integer generationTimeMs) {
        this.generationTimeMs = generationTimeMs;
    }

    public String getModelVersion() {
        return modelVersion;
    }

    public void setModelVersion(String modelVersion) {
        this.modelVersion = modelVersion;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }
}
